name: LobbyPlugin
version: 1.2
main: net.juligames.lobbyplugin.LobbyPlugin
authors:
  - TDRStudios
api-version: 1.15
permissions:
  tdrstudios.lobby.perms.fix.inventory:
    default: not op
commands:
   setspawn:
     description: Setze den Spawnpunkt mit /setspawn
     usage: /<command>
   spawn:
     description: Teleportiere dich zum Spawn mit /spawn
     usage: /<command>
   setlobbyWarp1:
     description: Setze den Spawnpunkt für das erste Lobbyitem mit /setlobbyspawn1
     usage: /<command>
   setlobbyWarp2:
     description: Setze den Spawnpunkt für das 2te Lobbyitem mit /setlobbyspawn2
     usage: /<command>
   setlobbyWarp3:
     usage: /<command>
     description: Setze den Spawnpunkt für das 3te Lobbyitem mit /setlobbyspawn3
   setlobbyWarp4:
     usage: /<command>
     description: Setze den Spawnpunkt für das 4te Lobbyitem mit /setlobbyspawn4
   setlobbyWarp5:
     usage: /<command>
     description: Setze den Spawnpunkt für das 5te Lobbyitem mit /setlobbyspawn5
   gm:
     description: Ändere deinen Gamemode mit /gm [0] [1] [2] [3]
     usage: /<command> [0] [1] [2] [3] <Player>
   gamemode:
     description: Ändere deinen Gamemode mit /gamemode [0] [1] [2] [3]
     usage: /<command> [0] [1] [2] [3] <Player>
   lv:
     usage: /<command>
     description: Zeige die Version vom Plugin an.
   lobbyversion:
     usage: /<command>
     description: Zeige die Version vom Plugin an.
   config:
    usage: /<command> [save] [read]
    description: This command is only for the debug!
   fixinventory:
     usage: /<command> <Player/'*'>
     description: Reset the inventory of a player
   fixinv:
     usage: /<command> <Player/'*'>
     description: Reset the inventory of a player