name: LobbyPlugin
version: 1.2
main: net.juligames.lobbyplugin.LobbyPlugin
authors:
  -TDRStudios

commands:
   setspawn:
     description: Setze den Spawnpunkt mit /setspawn
   spawn:
     description: Teleportiere dich zum Spawn mit /spawn
   setlobbyWarp1:
     description: Setze den Spawnpunkt für das erste Lobbyitem mit /setlobbyspawn1
   setlobbyWarp2:
     description: Setze den Spawnpunkt für das 2te Lobbyitem mit /setlobbyspawn2
   setlobbyWarp3:
     description: Setze den Spawnpunkt für das 3te Lobbyitem mit /setlobbyspawn3
   setlobbyWarp4:
     description: Setze den Spawnpunkt für das 4te Lobbyitem mit /setlobbyspawn4
   setlobbyWarp5:
     description: Setze den Spawnpunkt für das 5te Lobbyitem mit /setlobbyspawn5
   gm:
     description: Ändere deinen Gamemode mit /gm [0] [1] [2] [3]
   lv:
     description: Zeige die Version vom Plugin an.
   lobbyversion:
     description: Zeige die Version vom Plugin an.